### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by wyliebutler**

### CODE REVIEW

**Comment by modem7** [comment]
Heya,

Not quite sure the purpose of the pull request?

**Comment by wyliebutler** [comment]
I'm testing at this point.  I have not added my unique words etc.   At this stage it's a lot of learning :-)

**Comment by wyliebutler** [comment]
Dockerfile not found at ./Dockerfile   This is the error I get on Dockerhub.  Any suggestion?  And thanks for the quick response!

**Comment by modem7** [comment]
Best bet is to have a unique fork rather than create pull requests for this repo as I'll be keeping this repo as close to the [original ](https://github.com/cwackerfuss/react-wordle) as possible bar a few changes in the code/keeping dependencies updated.

**Pull request closed without merging**
